apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bar.fullname" . }}-backend-secret
  labels:
    {{- include "bar.backend.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.backend.env.BAR_API_KEY | b64enc | quote }}