apiVersion: v1
kind: Pod
metadata:
  name: vision-app-demo
  labels:
    app: vision-app-demo
spec:
  containers:
    - name: gradio
      image: mendeza/vision_analytics_demo:0.0.1
      ports:
        - containerPort: 7860
      resources:
        requests:
          cpu: "4"
          memory: "10Gi"
        limits:
          cpu: "4"
          memory: "10Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: vision-app-service
spec:
  selector:
    app: vision-app-demo
  ports:
    - protocol: TCP
      port: 7860
      targetPort: 7860
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: gradio-stream-virtualservice
  namespace: andrew-mendez-94dbc511
spec:
  hosts:
    - vision-app.ingress.pcai0109.sv11.hpecolo.net
  gateways:
    - istio-system/ezaf-gateway
  http:
    - match:
        - uri:
            prefix: /
      rewrite:
        uri: /
      route:
        - destination:
            host: vision-app-service.andrew-mendez-94dbc511.svc.cluster.local
            port:
              number: 7860