apiVersion: v2
name: bar
description: Batch Agreement Robot - AI-powered batch document analysis
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/your-org/bar
keywords:
  - document-analysis
  - ai
  - batch-processing
maintainers:
  - name: BAR Team
    email: bar-team@example.com