apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "onboarding-buddy.fullname" . }}-config
  labels:
    {{- include "onboarding-buddy.labels" . | nindent 4 }}
data:
  config.json: |-
    {
      "ai": {
        "endpoint": "{{ .Values.ai.endpoint }}",
        "model": "{{ .Values.ai.model }}",
        "config": {{ toJson .Values.ai.config | indent 8 }}{{ if .Values.ai.apiKey.value }},
        "apiKey": "{{ .Values.ai.apiKey.value }}"{{ end }}
      }
    }
