{{- if and .Values.ai.apiKey.secret.name .Values.ai.apiKey.secret.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ai.apiKey.secret.name }}
  labels:
    {{- include "onboarding-buddy.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.ai.apiKey.secret.key }}: {{ .Values.ai.apiKey.value | quote }}
{{- end }}
