apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Release.Name }}-deploy
  name: {{ .Release.Name }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: port-1
    port: {{ .Values.service.appPort }}
    targetPort: {{ .Values.service.appPort }}
  selector:
    app: {{ .Release.Name }}
status:
  loadBalancer: {}