apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "mock-support-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mock-support-app.labels" . | nindent 4 }}
spec:
  gateways:
    - {{ .Values.ezua.virtualService.istioGateway }}
  hosts:
    - {{ .Values.ezua.virtualService.endpoint }}
  #The following virtualService options are specific and depend on the application implementation.
  #This example is a simple application with single service and simple match routes.
  #The URL should point to the corresponding service. 
  #Kubernetes provides an internal DNS mapping for services using the format <ServiceName>.<ServiceNamespace>.svc.cluster.local. 
  http:
    - match:
        - uri:
            prefix: /
      rewrite:
        uri: /
      route:
        - destination:
            host: {{ include "mock-support-app.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.service.port }}
    - match:
        - uri:
            prefix: /api
      rewrite:
        uri: /api
      route:
        - destination:
            host: {{ include "mock-support-app.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 3001