
settings:
  Chatmodel: ""
  Chatmodelbaseurl: ""
  Chatmodelkey: "fake"
  Database: "/app/Chinook.sqlite"
  DatabasePath: "./db/"
  DatabaseType: "sqlite"

image:
  repository: vmtyler/pdk
  pullPolicy: IfNotPresent
  tag: vanna-0.0.4g

service:
  type: ClusterIP
  port: 8084

volumes: []
volumeMounts: []


ezua:
  enabled: true
  virtualService:
    endpoint: ""
    istioGateway: "istio-system/ezaf-gateway"
