
settings:
  Chatmodel: ""
  Chatmodelbaseurl: ""
  Chatmodelkey: "fake"
  Database: "/app/purchase_orders.sqlite"
  DatabasePath: "./db/"
  DatabaseType: "sqlite"

image:
  repository: mendeza/vanna-tulane-demo
  pullPolicy: IfNotPresent
  tag: 0.0.1

service:
  type: ClusterIP
  port: 8084

volumes: []
volumeMounts: []


ezua:
  enabled: true
  virtualService:
    endpoint: "vannai.${DOMAIN_NAME}"
    istioGateway: "istio-system/ezaf-gateway"
