# Default values for onboarding-buddy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: your-registry/onboarding-buddy
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

# Resource requests and limits
resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

# Ezmeral Unified Analytics (EzUA) Configuration
ezua:
  virtualService:
    # The endpoint where the service will be accessible (e.g., "service-name.${DOMAIN_NAME}")
    endpoint: "onboarding-buddy.example.com"
    # The Istio Gateway to use (e.g., "istio-system/ezaf-gateway")
    istioGateway: "istio-system/ezaf-gateway"

# Application configuration
app:
  # Environment variables to inject into the application pod
  envVars: {}

# AI Configuration
ai:
  # AI endpoint URL (e.g., https://api.openai.com/v1/chat/completions)
  endpoint: "https://api.openai.com/v1/chat/completions"
  # AI model to use
  model: "Meta/Llama-3.1-8B-Instruct"
  # Additional AI configuration parameters
  config:
    temperature: 0.7
    maxTokens: 2048
  # API Key configuration
  apiKey:
    # Option 1: Directly specify the API key (not recommended for production)
    # value: "your-api-key-here"
    
    # Option 2: Reference a Kubernetes secret (recommended)
    secret:
      name: ""  # Name of the Kubernetes secret
      key: "apiKey"  # Key within the secret that contains the API key
