apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "medical-summary-app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "medical-summary-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "medical-summary-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "medical-summary-app.name" . }}
    spec:
      containers:
        - name: {{ include "medical-summary-app.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: {{ .Values.service.name }}
          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data-storage
              mountPath: {{ .Values.persistence.mountPath | default "/app/data" }}
              {{- if .Values.persistence.subPath }}
              subPath: {{ .Values.persistence.subPath }}
              {{- end }}
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data-storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
      {{- end }}
